export const SET_LOADING = 'SET_LOADING';
export const SET_NUMBER_OF_POKEMON = 'SET_NUMBER_OF_POKEMON';
export const SET_POKEMON_LIST = 'SET_POKEMON_LIST';
export const SET_OFFSET = 'SET_OFFSET';
export const SET_SEARCH_INPUT_VALUE = 'SET_SEARCH_INPUT_VALUE';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SET_RECENT_SEARCHES = 'SET_RECENT_SEARCHES';
export const SET_POKEDEX_STATE = 'SET_POKEDEX_STATE';
