export const SET_NUMBER_OF_POKEMON = 'SET_NUMBER_OF_POKEMON';
export const SET_POKEMON_LIST = 'SET_POKEMON_LIST';
export const SET_OFFSET = 'SET_OFFSET';
export const SET_POKEDEX_STATE = 'SET_POKEDEX_STATE';
